#!/usr/bin/env bash
baseDir=$(dirname $0)
showHelp(){
    $baseDir/launcher.php --help
    return 0
}
runPHP(){
    $baseDir/launcher.php $*
}

for p in $*
do
    [[ $p = '--help' ]] && showHelp && exit 0
done
runPHP $*
